### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sonnguyen129** [kathrinse/TabSurvey#11]
Hi @kathrinse, I have been working with your repo for a short time and I like it very much. Can I create a modified version based on this repo (not fork)? I will mention your repo in my acknowledgment.

**Comment by kathrinse** [comment]
Hey @sonnguyen129,
thanks for asking! Of course you can use our repository as basis for your own projects - we created it to help the community :)
But please, cite our paper and refer to this repository.

**Comment by sonnguyen129** [comment]
Thanks for your reply.  I will do it.
