### ISSUE TITLE
Optimal hyperparameters?

### ISSUE THREAD

**Issue by mgreenbe** [kathrinse/TabSurvey#3]
Would it be possible to publish (e.g., in the README) the optimal hyperparameters that are used to generate the data in Table IV of the paper? This would make reproducing your results much more convenient!

**Comment by ColinTr** [comment]
I believe you can find them in the file : [TabSurvey/config/best_params.yml](https://github.com/kathrinse/TabSurvey/blob/main/config/best_params.yml)

**Comment by kathrinse** [comment]
Yes, Colin is right. We listed all the optimal hyperparameters in the best_params.yml file :)
