### ISSUE TITLE
Did the experiments of SAINT eliminate the influence of the pre-training process?

### ISSUE THREAD

**Issue by dorazhang93** [kathrinse/TabSurvey#4]
Hi, thanks for this insightful survey on DL for tabular data. And I want to ask for more details about the experiments on SAINT models. 
Did the experiments of SAINT eliminate the influence of the pre-training process? Or the model of the reported results is finetuned on the unsupervised pre-training model.  I failed to find a description of this in the article, so I will appreciate it if you answer it. Thanks!

**Comment by kathrinse** [comment]
We didn't do any pre-training steps for the SAINT model, we just trained it supervised from scratch on our data :)

But we might include this in some further experiments in the future.

**Comment by dorazhang93** [comment]
Then it's indeed a strong baseline for DL models. Though I don't really understand the mechanism underlying the row transformer. Did you also do the ablation experiments on two kinds of transformers? Because in the original article, it seems row transformer contributes more than column one.

**Comment by kathrinse** [comment]
Currently, we only tried the combination of both column and row attention.
Thanks for your question, we will think about including experiments only using the intersample attention!

But if you have more question to the SAINT paper (like how the row transformer works), it is probably better to ask the authors directly (https://github.com/somepago/saint) :)
